Remove MM registration in odesign
This involve a error

java.lang.IllegalStateException: Couldn't register package null because
its name is null.
	at org.eclipse.acceleo.query.runtime.impl.EPackageProvider.registerPackage(EPackageProvider.java:282)
	at org.eclipse.acceleo.query.runtime.impl.QueryEnvironment.registerEPackage(QueryEnvironment.java:94)

Signed-off-by: Hugo Marchadour <hugo.marchadour@obeo.fr>